// 对方userID
export const TARGET = 'TARGET'
// 对方信息
export const TARGETDETAIL = 'TARGETDETAIL'
// 聊天记录
export const MESSAGELIST = 'MESSAGELIST'
// 插入单条messagelist
export const INSERTONEROWMESSAGELIST = 'INSERTONEROWMESSAGELIST'
// 收到的未读消息列表
export const UNREADMESSAGELIST = 'UNREADMESSAGELIST'
// 插入单条未读消息
export const INSERTONEROWUNREADMESSAGELIST = 'INSERTONEROWUNREADMESSAGELIST'
// 朋友列表
export const FRIENDLIST = 'FRIENDLIST'